import type { AgentRole, SprintPhase } from '../../types/agent.ts';

export const PHASE_PATTERNS: Map<SprintPhase, RegExp[]> = new Map([
  [
    'think',
    [
      /brainstorm/i,
      /idea/i,
      /what.?if/i,
      /office.?hours/i,
      /product/i,
      /vision/i,
      /strategy/i,
      /direction/i,
      /explore/i,
      /consider/i,
      /what.?do.?you.?think/i,
      /discuss/i,
      /perspective/i,
      /opinion/i,
      /should.?we/i,
      /how.?about/i,
      /pros.?and.?cons/i,
      /trade.?off/i,
    ],
  ],
  [
    'plan',
    [
      /\bplan\b/i,
      /architect/i,
      /design/i,
      /structure/i,
      /organize/i,
      /approach/i,
      /break.?down/i,
      /scope/i,
      /estimate/i,
      /requirement/i,
      /spec/i,
      /rfc/i,
      /how.?should.?we/i,
      /technical.?design/i,
    ],
  ],
  [
    'build',
    [
      /implement/i,
      /\bbuild\b/i,
      /\bcode\b/i,
      /\bcreate\b/i,
      /add.?feature/i,
      /\bwrite\b/i,
      /\bfix\b/i,
      /\brefactor\b/i,
      /\bchange\b/i,
      /\bmodify\b/i,
      /\bupdate\b/i,
      /\badd\b/i,
      /\bremove\b/i,
      /\bdelete\b/i,
      /make.?it/i,
      /set.?up/i,
    ],
  ],
  [
    'review',
    [
      /\breview\b/i,
      /\bcheck\b/i,
      /\baudit\b/i,
      /second.?opinion/i,
      /\bcodex\b/i,
      /look.?at.?(?:my|this|the)/i,
      /code.?review/i,
      /pull.?request/i,
      /feedback/i,
      /\bcritique\b/i,
      /\bassess\b/i,
    ],
  ],
  [
    'test',
    [
      /\btest\b/i,
      /\bqa\b/i,
      /\bbrowse\b/i,
      /benchmark/i,
      /\bverify\b/i,
      /\bbug\b/i,
      /\bdebug\b/i,
      /\bbreak(?:ing|s)?\b/i,
      /\bfail(?:ing|s|ed)?\b/i,
      /not.?working/i,
      /broken/i,
      /regression/i,
      /\bflaky\b/i,
      /investigate/i,
      /trace/i,
      /diagnose/i,
      /reproduce/i,
    ],
  ],
  [
    'ship',
    [
      /\bship\b/i,
      /\bdeploy\b/i,
      /\brelease\b/i,
      /\bland\b/i,
      /\bmerge\b/i,
      /\bpr\b/i,
      /push.?to/i,
      /go.?live/i,
      /publish/i,
      /\bversion\b/i,
      /changelog/i,
      /cut.?a.?release/i,
    ],
  ],
  [
    'reflect',
    [
      /\bretro\b/i,
      /retrospective/i,
      /\bstats\b/i,
      /how.?did.?we.?do/i,
      /lessons?\s*learn/i,
      /what.?went/i,
      /improve/i,
      /sprint.?review/i,
    ],
  ],
  [
    'cross-cutting',
    [
      /\bcareful\b/i,
      /\bfreeze\b/i,
      /\bguard\b/i,
      /\bunfreeze\b/i,
      /\bdangerous\b/i,
      /\bdestructive\b/i,
      /\bproduction\b/i,
      /\brisky\b/i,
    ],
  ],
  ['utility', [/\bupgrade\b/i, /setup.?browser/i, /cookies/i, /\bdependenc/i, /\bpackage\b/i]],
]);

export const SKILL_TO_PHASE_MAP: Readonly<Record<string, SprintPhase>> = {
  'office-hours': 'think',
  'plan-ceo-review': 'think',
  'plan-eng-review': 'plan',
  'plan-design-review': 'plan',
  review: 'review',
  'design-consultation': 'plan',
  codex: 'review',
  careful: 'cross-cutting',
  freeze: 'cross-cutting',
  guard: 'cross-cutting',
  unfreeze: 'cross-cutting',
  investigate: 'build',
  retro: 'reflect',
  ship: 'ship',
  'land-and-deploy': 'ship',
  'setup-deploy': 'ship',
  'document-release': 'ship',
  browse: 'test',
  qa: 'test',
  'qa-only': 'test',
  'design-review': 'plan',
  benchmark: 'test',
  canary: 'ship',
  'setup-browser-cookies': 'utility',
  upgrade: 'utility',
};

export const PHASE_TO_DEFAULT_AGENT: Readonly<Record<SprintPhase, AgentRole>> = {
  think: 'ceo',
  plan: 'eng-manager',
  build: 'builder',
  review: 'reviewer',
  test: 'qa-lead',
  ship: 'release-engineer',
  reflect: 'retro-lead',
  'cross-cutting': 'safety-guard',
  utility: 'upgrader',
};
